@SOLID_Principles_HostAddress = http://localhost:5077

GET {{SOLID_Principles_HostAddress}}/api/User
Content-Type: application/json

###

GET {{SOLID_Principles_HostAddress}}/api/User(1002)
Content-Type: application/json

###

POST {{SOLID_Principles_HostAddress}}/api/User
Content-Type: application/json

{
  "name": "Created User",
  "email": "created_user@gmail.com"
}

###

GET {{SOLID_Principles_HostAddress}}/api/Expense
Content-Type: application/json

###

POST {{SOLID_Principles_HostAddress}}/api/Expense
Content-Type: application/json

{
  "userId": 1,
  "amount": 500,
  "category": 2,
  "date": "2024-11-22",
  "description": "An expense of another category type"
}